### ISSUE TITLE
MessageConverter and related implementation use Vert.x Kafka client classes

### ISSUE THREAD

**Issue by ppatierno** [strimzi/amqp-kafka-bridge#63]
After moving to use the Vert.x Kafka Client, the MessageConverter and related implementation should use the record classes provided from the Vert.x Kafka Client and not from the native Kafka client anymore.

**Comment by pushpithaDilhan** [comment]
I would like to work on this. Earlier I sent a PR but then closed because of some exceptions between the difference of libraries. I am working on those exceptions and will send the PR.
