### ISSUE TITLE
Having "key" field with null value in converted message

### ISSUE THREAD

**Issue by ppatierno** [strimzi/amqp-kafka-bridge#79]
Currently the converters get rid of the message "key" if it's null. It could be better having the "key" field in the converted message (i.e. as AMQP annotation) but with null value instead of not having it at all.

**Comment by shubhamvashisht** [comment]
I would love to work on this issue.

**Comment by scholzj** [comment]
Sounds quite straight forward to me. Fell free to have a look at it.
