### ISSUE TITLE
C100K MQTT Connections Support with MQTT over AMQP

### ISSUE THREAD

**Issue by yhilem** [strimzi/amqp-kafka-bridge#86]
Hi,
I am in a study phase for the choice of an MQTT solution for data exchange with a fleet of 90000 android smartphones.
Our back-end is based on kafka (https://github.com/strimzi/amqp-kafka-bridge/issues/83).
My question: are these components (https://github.com/EnMasseProject/enmasse/tree/master/documentation/design_docs/mqtt-over-amqp) and (https://github.com/strimzi/amqp-kafka-bridge) designed to support 100K> connections?
If yes, did you have a link to an example / bench to test quickly?

Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
Hi,
we don't have such an example/bench for testing it. For sure the AMQP side of EnMasse is able to do that but we have to test the MQTT gateway part and the bridge itself.
At same time, consider that the bridge is evolving to support multiple protocols and the EnMasse MQTT gateway can be avoided in this case.

**Comment by yhilem** [comment]
Hi,
You say that this bridge is evolving to support multiple protocols.
What are these protocols ?
Our primary need is for mobile device protocols.
I have already explored the two solutions (https://github.com/zalando/nakadi) and (https://github.com/allegro/hermes) that offer HTTP for kafka.
Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
Hi,
I see that such a solutions are naming themselves as "message broker" or "distribuited abstraction" on top of Kafka. In our case, we have a gateway/bridge for translation protocol so something more lightweight but I should dig into the above solutions for having a better idea about what they offer. Regarding other protocols support, HTTP is on the roadmap as well.

**Comment by yhilem** [comment]
Hi,
It seems that Vert.x Proton is Android compatible (https://github.com/eclipse/vert.x/issues/2110).
In this case I can do without the gateway mqtt like (https://github.com/ppatierno/amqp-kafka-demo#amqp-vertx-proton).
Then the question becomes simple: is this bridge designed to support a load of 100K conccurent connection ?
Thanks
Youcef HILEM

**Comment by lulf** [comment]
@yhilem If you use vert.x proton (AMQP) on the client side (which I would recommend over MQTT for your case) one option is to put a Qpid Dispatch Router in front of the bridge. It is designed to handle a large number of connections (and you can connect multiple routers if you need to handle more) and a high throughput. You can then configure it to route traffic to the bridge (of which you can configure multiple instances) if needed based on your load. The router is quite flexible if you want to distribute data to multiple data centers etc.

The next question is what throughput and latency requirements do you have for your clients?

**Comment by ppatierno** [comment]
thanks @lulf for jumping into it. I'd like to add that it's also possible to have more than one router in order to handle more connections to the devices side. In such a configuration (one or more router), the bridge can work in "client" mode connecting to the broker with only one connection so it doesn't need to handle tons of connections relying on the router(s). Using the AMQP protocol, which is multiplexed, the attached links on the router side "will live" as links into this one connection to the bridge in order to read/write Kafka topic on the other side then. Of course, having more than one bridge can help based on the load.

**Comment by yhilem** [comment]
Thank you.
In this case I still have to study Qpid Dispatch Router and see how to use some Enmasse components  (http://enmasse.io/) on our RedHat Openshift 3.6 and kafka.
Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
@yhilem takes into account that you could even start just using the Qpid Dispatch Router (one or more instances) alongside with the AMQP - Kafka bridge without the need for the entire EnMasse project.
